version: '3'

services:
  redis:
    image: redis
    command: redis-server
    ports:
      - 7001:6379
    deploy:
      resources:
        limits:
          memory: 2048M
        reservations:
          memory: 1024M
    volumes:
      - /root/weibospider/data/redis:/data
    container_name: weibo-redis
